// <auto-generated />
using System;
using LP.Bank.Infra.Data.Bank;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LP.Bank.Infra.Data.Accounts.Migrations
{
    [DbContext(typeof(BankAccountsDbContext))]
    [Migration("20230118021002_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LP.Bank.Domain.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Ammount")
                        .HasColumnType("numeric")
                        .HasColumnName("ammount");

                    b.Property<decimal>("Number")
                        .HasColumnType("numeric")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.ToTable("bank_account", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
