// <auto-generated />
using System;
using LP.Bank.Infra.Data.Bank;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LP.Bank.Infra.Data.Accounts.Migrations
{
    [DbContext(typeof(BankAccountsDbContext))]
    [Migration("20230118022023_FillAccountsTable")]
    partial class FillAccountsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LP.Bank.Domain.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Ammount")
                        .HasColumnType("numeric")
                        .HasColumnName("ammount");

                    b.Property<decimal>("Number")
                        .HasColumnType("numeric")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.ToTable("bank_account", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0cdc56fe-94a6-4bec-9c66-1ee8320f8fb8"),
                            Ammount = 999m,
                            Number = 8445865m
                        },
                        new
                        {
                            Id = new Guid("35a71451-1fe9-459b-a88c-80b60238de50"),
                            Ammount = 50m,
                            Number = 9224968m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
